---
- name: fetch additional apps
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    version: '{{ item.version }}'
  with_items:
    - { repo: 'https://gitlab.com/fdroid/fdroidclient', dest: /var/lib/aosp8/packages/apps/fdroid, version: stable-v0.102 }
    - { repo: 'https://github.com/LineageOS/android_packages_apps_Browser.git', dest: /var/lib/aosp8/packages/apps/Browser, version: cm-14.1 }
    - { repo: 'https://github.com/LineageOS/android_packages_apps_CMFileManager.git', dest: /var/lib/aosp8/packages/apps/CMFileManager, version: cm-14.1 }
    - { repo: 'https://github.com/LineageOS/android_external_libtruezip.git', dest: /var/lib/aosp8/external/libtruezip, version: cm-14.1 }
    - { repo: 'https://github.com/LineageOS/android_external_cyanogen_UICommon.git', dest: /var/lib/aosp8/external/uicommon, version: cm-14.1 }

- name: replace product package list
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: user
    group: user
    mode: 0640
  with_items:
    - { src: var/lib/aosp8/build/target/product/core.mk.j2, dest: /var/lib/aosp8/build/target/product/core.mk }
